Repository expressots/expressots, pull requests merged in 2023-07, with the labels that each got.

#37 feat: add render engine mechanic and handlebars sup
  packages/core/src/application/application.ts
  packages/core/src/controller/base-controller.ts
  packages/core/src/index.ts
  packages/core/src/render/handlebars.interface.ts
  packages/core/src/render/index.ts
  packages/core/src/render/render.type.ts
Labels: enhancement

#40 Fix broken url on readme
  README.md
Labels: documentation, good first issue

#41 fix: add 404 on opinionated template user usecases
  templates/opinionated/src/useCases/user/delete/user-delete.usecase.ts
  templates/opinionated/src/useCases/user/find/user-find.usecase.ts
  templates/opinionated/src/useCases/user/update/user-update.usecase.ts
Labels: enhancement

#42 Ets 272 remove from the env validator provider the check of all os env variables
  packages/core/src/environment/env-validator.ts
Labels: enhancement

#43 feat: add community ideas form
  .github/ISSUE_TEMPLATE/community_ideas.yml
Labels: documentation, enhancement

#44 fix: add workflow for auto project and label
  .github/workflows/community-idea.yml
Labels: enhancement

#58 feat(prettier): add a prettier config and run it in the core package
  package.json
  packages/core/jest.config.ts
  packages/core/src/application/app-container.ts
  packages/core/src/application/application.ts
  packages/core/src/application/index.ts
  packages/core/src/common/index.ts
  packages/core/src/common/project-config.provider.ts
  packages/core/src/console/console.ts
  packages/core/src/console/index.ts
  packages/core/src/container-module/container-module.ts
  packages/core/src/container-module/index.ts
  packages/core/src/controller/base-controller.ts
  packages/core/src/controller/index.ts
  packages/core/src/decorator/index.ts
  packages/core/src/decorator/scope-binding.ts
  packages/core/src/environment/env-validator.ts
  packages/core/src/environment/index.ts
  packages/core/src/error/error-handler-middleware.ts
  packages/core/src/error/index.ts
  packages/core/src/error/report.ts
  packages/core/src/error/status-code.ts
  packages/core/src/index.ts
  packages/core/src/logger/general-logger.ts
  packages/core/src/logger/index.ts
  packages/core/src/render/handlebars.interface.ts
  packages/core/src/render/index.ts
  packages/core/test/application.spec.ts
  packages/core/test/console.spec.ts
  packages/core/test/env-validator.spec.ts
  prettier.config.mjs
Labels: enhancement
