Repository expressots/expressots, pull requests merged in 2023-08, with the labels that each got.

#60 feat: add dependabot for fetch new version of dependencies
  .github/dependabot.yml
Labels: enhancement, analysis

#71 feat: add prisma provider configuration types in ExpressoConfig
  packages/core/src/common/project-config.provider.ts
Labels: enhancement

#73 fix: add `options` parameter to `AppContainer`
  packages/core/src/application/app-container.ts
Labels: enhancement

#76 fix: increase the event range for graceful shutdown
  packages/core/src/application/application.ts
Labels: enhancement

#78 fix: remove verb should from unit tests labels
  packages/core/test/application.spec.ts
  packages/core/test/console.spec.ts
  templates/non_opinionated/test/app.usecase.spec.ts
  templates/opinionated/test/app.usecase.spec.ts
Labels: enhancement

#83 feat: add benchmark folder
  benchmark/benchmark.js
  benchmark/express.js
  benchmark/expressots/app.container.ts
  benchmark/expressots/app.controller.ts
  benchmark/expressots/app.module.ts
  benchmark/expressots/app.usecase.ts
  benchmark/expressots/main.ts
  benchmark/fastify.js
  benchmark/happi.js
  benchmark/nest.js
  benchmark/nestjs/app.controller.d.ts
  benchmark/nestjs/app.controller.js
  benchmark/nestjs/app.controller.js.map
  benchmark/nestjs/app.module.d.ts
  benchmark/nestjs/app.module.js
  benchmark/nestjs/app.module.js.map
  benchmark/nestjs/main.d.ts
  benchmark/nestjs/main.js.map
Labels: documentation, enhancement
