Repository expressots/expressots, pull requests merged in 2023-09, with the labels that each got.

#85 Fix/linter prettier precommit
  .eslintrc.cjs
  .husky/commit-msg
  .prettierrc
  package.json
  packages/core/src/application/app-container.ts
  packages/core/src/application/application.ts
  packages/core/src/common/project-config.provider.ts
  packages/core/src/console/console.ts
  packages/core/src/container-module/container-module.ts
  packages/core/src/controller/base-controller.ts
  packages/core/src/decorator/scope-binding.ts
  packages/core/src/environment/env-validator.ts
  packages/core/src/error/error-handler-middleware.ts
  packages/core/src/logger/general-logger.ts
  tsconfig.base.json
  tsconfig.cjs.json
  tsconfig.esm.json
Labels: enhancement

#86 fix: add generic in memory db and virtual table analysis
  templates/opinionated/src/providers/db-in-memory/db-in-memory.provider.ts
  templates/opinionated/src/repositories/base-repository.ts
  templates/opinionated/src/repositories/user/user.repository.ts
Labels: enhancement

#88 ci: config test workflow and setup vitest
  .eslintrc.cjs
  .github/workflows/codeql-analysis.yml
  .github/workflows/core-lib-ci-cd.yaml
  .github/workflows/core-lib-ci-cd.yml
  jest.config.ts
  package.json
  packages/core/jest.config.ts
  packages/core/test/application.spec.ts
  packages/core/test/console.spec.ts
  packages/core/test/env-validator.spec.ts
  tsconfig.base.json
  vitest.config.ts
Labels: enhancement

#89 hotfix: middleware needs next parameter
  CHANGELOG.md
  packages/core/src/application/application.ts
  packages/core/src/error/app-error.ts
  packages/core/src/error/error-handler-middleware.ts
  packages/core/src/error/index.ts
  packages/core/src/error/report.ts
Labels: bug

#91 fix: use new report utility in usecases
  templates/opinionated/src/useCases/user/create/user-create.usecase.ts
  templates/opinionated/src/useCases/user/delete/user-delete.usecase.ts
  templates/opinionated/src/useCases/user/find/user-find.usecase.ts
  templates/opinionated/src/useCases/user/update/user-update.usecase.ts
Labels: bug

#90 refactor: update type from any to number
  packages/core/src/console/console.ts
Labels: enhancement

#94 Feature/dto validator
  package.json
  packages/core/src/common/color-service.provider.ts
  packages/core/src/common/package-resolver.provider.ts
  packages/core/src/console/console.ts
  packages/core/src/controller/base-controller.ts
  packages/core/src/environment/index.ts
  packages/core/src/error/report.ts
  packages/core/src/index.ts
  packages/core/src/logger/index.ts
  packages/core/src/provider/dto-validator/dto-validator.provider.ts
  packages/core/src/provider/environment/env-validator.provider.ts
  packages/core/src/provider/index.ts
  packages/core/src/provider/logger/logger-service.ts
  packages/core/src/provider/logger/winston-logger.ts
  packages/core/src/provider/provider-service.ts
  packages/core/test/console.spec.ts
  packages/core/test/env-validator.spec.ts
  templates/opinionated/package.json
  templates/opinionated/src/useCases/user/create/user-create.controller.ts
  templates/opinionated/src/useCases/user/create/user-create.dto.ts
  templates/opinionated/src/useCases/user/create/user-create.usecase.ts
  templates/opinionated/src/useCases/user/delete/user-delete.controller.ts
  templates/opinionated/src/useCases/user/delete/user-delete.dto.ts
  templates/opinionated/src/useCases/user/delete/user-delete.usecase.ts
  templates/opinionated/src/useCases/user/find/user-find.controller.ts
  templates/opinionated/src/useCases/user/find/user-find.dto.ts
  templates/opinionated/src/useCases/user/find/user-find.usecase.ts
  templates/opinionated/src/useCases/user/findall/user-findall.controller.ts
  templates/opinionated/src/useCases/user/findall/user-findall.dto.ts
  templates/opinionated/src/useCases/user/findall/user-findall.usecase.ts
  templates/opinionated/src/useCases/user/update/user-update.controller.ts
  templates/opinionated/src/useCases/user/update/user-update.dto.ts
  templates/opinionated/src/useCases/user/update/user-update.usecase.ts
  templates/opinionated/tsconfig.build.json
  templates/opinionated/tsconfig.json
  tsconfig.base.json
Labels: bug, enhancement, dependencies

#95 fix: dto validator json structure per property
  packages/core/src/provider/dto-validator/dto-validator.provider.ts
Labels: enhancement

#96 Feature/small improvements
  .husky/commit-msg
  package.json
  packages/core/src/application/application-factory.ts
  packages/core/src/application/application.ts
  packages/core/src/application/index.ts
  packages/core/src/controller/base-controller.ts
  packages/core/src/decorator/scope-binding.ts
  packages/core/src/index.ts
  packages/core/src/middleware/index.ts
  packages/core/src/middleware/interfaces/body-parser.interface.ts
  packages/core/src/middleware/interfaces/compression.interface.ts
  packages/core/src/middleware/interfaces/cors.interface.ts
  packages/core/src/middleware/interfaces/serve-static.interface.ts
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/middleware/middleware-service.ts
  packages/core/src/provider/index.ts
  packages/core/test/application.spec.ts
Labels: enhancement

#97 Feature/v2
  package.json
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/provider/logger/winston-logger.ts
Labels: enhancement

#99 Cookie Session
  packages/core/src/middleware/index.ts
  packages/core/src/middleware/interfaces/cookie-session/cookie-session.interface.ts
  packages/core/src/middleware/interfaces/cookie-session/keygrip.interface.ts
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/middleware/middleware-service.ts
Labels: enhancement

#98 Cookie Parser
  packages/core/src/middleware/index.ts
  packages/core/src/middleware/interfaces/cookie-parser.interface.ts
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/middleware/middleware-service.ts
Labels: enhancement

#100 Serve favicon
  packages/core/src/middleware/index.ts
  packages/core/src/middleware/interfaces/serve-favicon.interface.ts
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/middleware/middleware-service.ts
Labels: enhancement

#101 [doc fix]: Fixing typos
  CONTRIBUTING_HOWTO.md
Labels: documentation

#103 Fix/multi middleware with path
  packages/core/src/middleware/middleware-service.ts
Labels: enhancement

#109 Feature/add express middlewares
  packages/core/src/middleware/index.ts
  packages/core/src/middleware/interfaces/morgan.interface.ts
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/middleware/middleware-service.ts
Labels: enhancement

#105 refactor: improve code readability
  packages/core/src/controller/base-controller.ts
Labels: enhancement

#111 Fix/adjust repo config
  package.json
  tsconfig.base.json
  tsconfig.cjs.json
Labels: enhancement

#112 Feature/add unit tests
  package.json
  packages/core/test/application.spec.ts
  packages/core/test/console.spec.ts
  vitest.config.ts
Labels: enhancement
