Repository expressots/expressots, pull requests merged in 2023-10, with the labels that each got.

#115 Feature: add rate limit middleware
  packages/core/src/middleware/index.ts
  packages/core/src/middleware/interfaces/express-rate-limit.interface.ts
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/middleware/middleware-service.ts
Labels: enhancement, good first issue, needs triage, hacktoberfest

#116 Feat(core): add helmet middleware
  packages/core/src/middleware/index.ts
  packages/core/src/middleware/interfaces/helmet.interface.ts
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/middleware/middleware-service.ts
Labels: enhancement, good first issue, needs triage, hacktoberfest

#122 fix: Auto setup husky with project setup and installation
  package.json
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#125 feat: Added express-session middleware for expressots
  packages/core/src/middleware/index.ts
  packages/core/src/middleware/interfaces/express-session.interface.ts
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/middleware/middleware-service.ts
Labels: enhancement, good first issue, hacktoberfest

#127 test: improve collocation and fix console tests
  packages/core/src/console/__tests__/console.spec.ts
  packages/core/src/provider/environment/__tests__/env-validator.spec.ts
  tsconfig.base.json
Labels: enhancement

#129 feat: add db in memory as provider
  .eslintrc.cjs
  packages/core/src/provider/db-in-memory/db-in-memory.provider.ts
  packages/core/src/provider/index.ts
Labels: enhancement

#120 feat: Added multer middleware for expressots
  packages/core/src/middleware/index.ts
  packages/core/src/middleware/interfaces/multer.interface.ts
  packages/core/src/middleware/middleware-resolver.ts
  packages/core/src/middleware/middleware-service.ts
Labels: enhancement, good first issue, hacktoberfest
